services:
  - type: web
    name: lachiennete
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: MESSENGER_TRANSPORT_DSN
        value: sync://
      - key: MAILER_DSN
        value: null://null
      - key: CORS_ALLOW_ORIGIN
        value: '^https://.*\.onrender\.com$'
      - key: DEFAULT_URI
        value: https://lachiennete.onrender.com
